### PR TITLE
9 Added class NotificationHandler that is capable of pushing notifications

### PR DESCRIPTION
**Pull request by limkokyew**
Not exactly ready to be merged into master - requesting feedback.

### CODE REVIEW

**Comment by craftamap** [comment]
Looks good so far!
One question: Will the notificationChannel be used in the future, or does it only need to be generated?

Please take a look at the detekt log, currrently the pipeline fails. :/

**Comment by limkokyew** [comment]
> One question: Will the notificationChannel be used in the future, or does it only need to be generated?
Starting from Android 8.0, all notifications must be associated with a channel, i. e. we need to create a Notification Channel only once.

I fixed the Detekt errors, but I won't merge yet - I want to take a look at how we can schedule notifications.

**Review by mac641 — APPROVED** [review]
Looking good 👍🏿

Some comments in later state of the app might be useful...

**Comment by craftamap** [comment]
Looks good to me!

**Review by diehmlukas — APPROVED** [review]

**Review by craftamap — APPROVED** [review]

**Pull request merged**
