### PR TITLE
42 Load state machine timer duration from config

### PR DESCRIPTION
**Pull request by mac641**
- Add SettingsConfig and adapt ConfigManager to be using SettingsConfig
- Add some sort of exception handling in CameraActivity when using `ConfigManager.load()`
- Minor refactoring / typo fixes

### CODE REVIEW

**Review by limkokyew — APPROVED** [review]
Looks good to me!

**Review by AnnaGsell — CHANGES_REQUESTED** [review]
please rename to TimerConfig

**Review by diehmlukas — CHANGES_REQUESTED** [review]
We need Long and no Float for the Timer and millisec instead of sec

**Comment by mac641** [comment]
> We need Long and no Float for the Timer and millisec instead of sec

State machine uses 2.5s as stimulus timer therefore Floats are appropriate -> **Please clarify**

**Comment by craftamap** [comment]
Looks good to me! I'd suggest to either use floats or to store millis here. Storing millis would propably be the "cleaner" solution.

**Review by AnnaGsell — APPROVED** [review]

**Review by diehmlukas — APPROVED** [review]

**Pull request merged**
